### **Python Pandas**

In [8]:
import pandas as pd

### **Series**

In [30]:
car_name = pd.Series(["TATA", "TOYOTA","BMW","HONDA", "AUDI"])
car_name

0      TATA
1    TOYOTA
2       BMW
3     HONDA
4      AUDI
dtype: str

In [31]:
print(car_name .dtypes)

str

In [33]:
print(car_name .shape)
print(car_name .size)

(5,)
5

In [34]:
print(car_name [2:4])

2      BMW
3    HONDA
dtype: str

In [35]:
car_name[1]= "Suzuki"
car_name

0      TATA
1    Suzuki
2       BMW
3     HONDA
4      AUDI
dtype: str

### **DataFrame**

In [36]:
car_name = pd.Series(["TATA", "TOYOTA","BMW","HONDA", "AUDI"])
car_name

0      TATA
1    TOYOTA
2       BMW
3     HONDA
4      AUDI
dtype: str

In [57]:
car_color = pd.Series(["Gray", "Red", "Black", "Blue", "White"])
car_color

0     Gray
1      Red
2    Black
3     Blue
4    White
dtype: str

In [58]:
car_data = pd.DataFrame({
    "Name" : car_name,
    "Color": car_color
})

car_data

     Name  Color
0    TATA   Gray
1  TOYOTA    Red
2     BMW  Black
3   HONDA   Blue
4    AUDI  White

In [59]:
print(car_data.dtypes)
print()
print(car_data.shape)
print()
print(car_data.size)

Name     str
Color    str
dtype: object

(5, 2)

10

In [60]:
car_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Color   5 non-null      str
dtypes: str(2)
memory usage: 212.0 bytes

In [61]:
car_data.isna().sum()

Name     0
Color    0
dtype: int64

In [64]:
df = pd.read_csv("C:\\Users\\manju\\Documents\\work\\AI- Class\\csv\\car_sales.csv")
df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [69]:
print(df.shape)
print()
print(df.size)
print()
print(df.dtypes)

(10, 5)

50

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [74]:
df.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [78]:
df.to_csv("Test.csv",index=False)

In [79]:
new_df= pd.read_csv("Test.csv")
new_df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

### **Head and Tail**

In [83]:
new_df.head(4)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [85]:
new_df.tail(3)

     Make Colour  Odometer (KM)  Doors      Price
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [87]:
new_df

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

### **loc,iloc ()**

In [89]:
# loc

new_df.loc[4:7]

     Make Colour  Odometer (KM)  Doors      Price
4  Nissan  White         213095      4  $3,500.00
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00

In [93]:
colour = pd.Series(['Red','Blue','Wight','Green','Black'],
                   index = [2,4,3,5,1])
colour

colour

2      Red
4     Blue
3    Wight
5    Green
1    Black
dtype: str

In [112]:
colour.loc[1:0]

KeyError: 'Cannot get right slice bound for non-monotonic index with a missing label 0. Either sort the index or specify an existing label.'

In [108]:
# iloc ()

colour.iloc[0:]

2      Red
4     Blue
3    Wight
5    Green
1    Black
dtype: str